kind: Service
apiVersion: v1
metadata:
  name: cert-manager
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9402
      targetPort: 9402
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager