apiVersion: broker.amq.io/v2alpha5
kind: ActiveMQArtemis
metadata:
  name: broker-a
spec:
  acceptors:
    - name: artemis
      expose: true
      protocols: 'amqp,core,stomp'
      port: 61617
      sslEnabled: true
      sslSecret: broker-a-jks
    - name: router
      protocols: amqp
      port: 5672
      sslEnabled: true
      sslSecret: broker-a-router-jks
      needClientAuth: true
  adminUser:  admin
  adminPassword: admin
  console:
    expose: true
  deploymentPlan:
    size: 1
    image: placeholder
    journalType: aio
    persistenceEnabled: true
    messageMigration: true
    requireLogin: false
    enableMetricsPlugin: true
    clustered: false
    initImage: image-registry.openshift-image-registry.svc:5000/amq-broker-custom/amq-broker-init:v0.1
