apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemis
metadata:
  name: broker-a
spec:
  acceptors:
    - name: artemis
      expose: true
      protocols: 'amqp,core,stomp'
      port: 61617
      sslEnabled: true
      sslSecret: broker-a-jks
    - name: router
      protocols: amqp
      port: 5672
      sslEnabled: true
      sslSecret: broker-a-router-jks
  adminUser:  admin
  adminPassword: admin
  console:
    expose: true
  deploymentPlan:
    size: 1
    image: registry.redhat.io/amq7/amq-broker:7.8
    journalType: aio
    persistenceEnabled: true
    messageMigration: true
    requireLogin: true
