apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: resource-locker-operator
spec:
  channel: alpha
  installPlanApproval: Manual
  name: resource-locker-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: resource-locker-operator.v1.1.3