apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: router-mesh-tls
spec:
  secretName: router-mesh-tls
  issuerRef:
    name: ca-issuer
  commonName: router-a
  usages:
    - server auth
    - client auth
  dnsNames:
  - router-a
  - router-a.amq-router.svc
  - router-a.amq-router.svc.cluster.local