apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: amq-tls
spec:
  secretName: amq-tls
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: amq-client
  usages:
    - client auth
  keyEncoding: pkcs8
  keystores:
    jks:
      create: true
      passwordSecretRef:
        name: amq-tls
        key: keyStorePassword
