{
 "title": "Apache Artemis",
 "description": "Dashboard for monitoring Apache Artemis",
 "tags": [ "apache artemis" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(jvm_memory_used_bytes, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(avg_over_time(jvm_memory_used_bytes{area=\"heap\", pod=\"$instance\", namespace=\"$namespace\"}[1m]))*100/sum(avg_over_time(jvm_memory_max_bytes{area=\"heap\", pod=\"$instance\", namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Persistent Size",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 0 },
   "format": "kbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(artemis_persistent_size{pod='$instance', namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Message Count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(artemis_message_count{pod='$instance',  namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Message Delivering",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(artemis_delivering_message_count{pod='$instance',  namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Started",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{pod=\"$instance\",  namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Message Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) ( artemis_message_count{pod=\"$instance\",  namespace=\"$namespace\"}  )",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Connections and Consumers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "artemis_connection_count{pod=\"$instance\",  namespace=\"$namespace\"}",
     "legendFormat": "Connection Count"
    },
    {
     "expr": "artemis_consumer_count{pod=\"$instance\",  namespace=\"$namespace\"}",
     "legendFormat": "{{ address }}"
    }
   ]
  },
  {
   "title": "Artemis Address Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "artemis_address_memory_usage{pod=\"$instance\",  namespace=\"$namespace\"}",
     "legendFormat": "{{ address }}"
    }
   ]
  }
 ]
}