apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: interconnect
spec:
  endpoints:
    - interval: 5s
      port: http
      scheme: http
  namespaceSelector:
    matchNames:
      - amq-router
  selector:
    matchLabels:
      application: router-a
      interconnect_cr: router-a
