apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
spec:
  endpoints:
    - interval: 5s
      port: tcp-prometheus-servicemonitor
      scheme: http
  namespaceSelector:
    matchNames:
      - openshift-operators
  selector:
    matchLabels:
      app: cert-manager