apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
spec:
  endpoints:
    - interval: 5s
      port: http
      scheme: http
  namespaceSelector:
    matchNames:
      - amq-certificates
  selector:
    matchLabels:
      app: cert-manager