apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: amq-broker
spec:
  endpoints:
    - interval: 30s
      port: console-jolokia
      scheme: http
  namespaceSelector:
    matchNames:
      - amq-broker-simple
      - amq-broker-sharded
  selector:
    matchLabels:
      application: broker-a-app