apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: amq-tls-patch-broker-simple
spec:
  serviceAccountRef:
    name: default
  patches:
  - id: amq-tls-patch-broker-simple
    sourceObjectRefs:
    - apiVersion: v1
      kind: Secret
      name: broker-simple-tls
      namespace: amq-certificates
    targetObjectRef:
      apiVersion: v1
      kind: Secret
      name: broker-a-jks
      namespace: amq-broker-simple
    patchType: application/strategic-merge-patch+json
    patchTemplate: |
      data:
        broker.ks: {{ (index (index . 0).data "keystore.jks") }}
        client.ts: {{ (index (index . 0).data "truststore.jks") }}