apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: client-tls-patch-broker-simple
spec:
  serviceAccountRef:
    name: default
  patches:
  - id: client-tls-patch-broker-simple
    sourceObjectRefs:
    - apiVersion: v1
      kind: Secret
      name: broker-simple-tls
      namespace: amq-certificates
    targetObjectRef:
      apiVersion: v1
      kind: Secret
      name: broker-simple-tls
      namespace: amq-client
    patchType: application/strategic-merge-patch+json
    patchTemplate: |
      data:
        truststore.jks: {{ (index (index . 0).data "truststore.jks") }}
