kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: amq-certificates
subjects:
  - kind: ServiceAccount
    name: default
    namespace: amq-certificates
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
