apiVersion: v1
kind: Secret
metadata:
  name: broker-sharded-tls
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
stringData:
  keyStorePassword: changeit
  trustStorePassword: changeit
  keyStorePath: /etc/broker-sharded-tls-volume/keystore.jks
  trustStorePath: /etc/broker-sharded-tls-volume/truststore.jks
